name: olu_ai
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.0
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.2
  path: ^1.9.0
  record: ^6.1.2
  permission_handler: ^12.0.1
  sherpa_onnx: ^1.12.23
  http: ^1.6.0
  llama_cpp_dart: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  drift_dev: ^2.20.0


flutter:

  uses-material-design: true

  assets:
    # ⬇️ REMOVE/COMMENT the lines below for Production Release to keep app size small
    - models/sherpa/
    - models/llm/

